-- ============================================================
-- PRIMARY OWNER: SK
-- ROLE: Core Platform + Backend Integration Lead
-- MODULE: Database Seed Data
-- NOTE: Shared dependency -- changes require team coordination.
-- ============================================================
-- ============================================================
-- PRIMARY OWNER: SK
-- ROLE: Core Platform + Backend Integration Lead
-- MODULE: Database Seed Data
-- NOTE: Shared dependency -- changes require team coordination.
-- ============================================================
-- ============================================================
-- PRIMARY OWNER: SK
-- ROLE: Core Platform + Backend Integration Lead
-- MODULE: Database Seed Data
-- NOTE: Shared dependency -- changes require team coordination.
-- ============================================================
